name: Discord Notification
  
on:
 workflow_run:
    workflows: ["http tests"]
    types:
      - completed


jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: GITHUB STATUS
        DISCORD_AVATAR: https://i.kym-cdn.com/photos/images/newsfeed/001/499/826/2f0.png
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new commit has been pushed and deployed (all tests passed).'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GITHUB STATUS
          DISCORD_AVATAR: https://pbs.twimg.com/media/EXWPKHvUcAEgtzQ.jpg
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new commit has been pushed but could not be deployed (tests did not passed).'
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
