# This is a basic workflow to help you get started with Actions

name: http tests

# Controls when the workflow will run
 
on:
 workflow_run:
    workflows: ["Sonar tests"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://deploiment-continue.herokuapp.com/user/deploy", "https://deploiment-continue.herokuapp.com/user/communisme"]'
        expected: '[200, 404]'
